root: true
extends:
  - '@swimlane'
  - prettier
overrides:
  - files:
      - '*.ts'
    parser: '@typescript-eslint/parser'
    parserOptions:
      project:
        - tsconfig.json
      createDefaultProgram: true
    extends:
      - '@swimlane/eslint-config/typescript'
      - plugin:@angular-eslint/recommended
      - plugin:@angular-eslint/template/process-inline-templates
      - prettier
    rules:
      '@typescript-eslint/no-explicit-any': off
      '@typescript-eslint/no-var-requires': off
  - files:
      - '*.html'
    extends:
      - plugin:@angular-eslint/template/recommended
