name: Build, Test, and Deploy

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          node-version: 22.16

      - name: Install
        uses: bahmutov/npm-install@v1
        with:
          install-command: npm ci --legacy-peer-deps

      - name: Build
        run: |
          npm run build --if-present
        env:
          CI: true

      - name: Build Storybook
        run: |
          npm run build:storybook
        env:
          CI: true

      - name: Test
        run: |
          npm run ci --if-present
        env:
          CI: true

      - name: Prepare and deploy
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: ./dist/storybook/ngx-dnd
          clean: true
        env:
          CI: true
